@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 04 21:16:57 -0700 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_conv_layer_behav -key {Behavioral:sim_1:Functional:tb_conv_layer} -tclbatch tb_conv_layer.tcl -view E:/Documents/EEE-598/CNN_verilog/sim/tb_conv_layer_behav.wcfg -log simulate.log"
call xsim  tb_conv_layer_behav -key {Behavioral:sim_1:Functional:tb_conv_layer} -tclbatch tb_conv_layer.tcl -view E:/Documents/EEE-598/CNN_verilog/sim/tb_conv_layer_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
